---

- name: Set authorized key took from files
  authorized_key:
    user: treeptik
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "./{{ FOLDER_SSH_KEYS }}/*"
