---

- debug:
    msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution }}"
    verbosity: 2

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim
  - curl
  - wget
  - git
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
