---

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim
  - curl
  - wget
  become: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution == "RedHat"
