---

- hosts: cluster_infra:&linux
  remote_user: treeptik

  roles:
    - monitoring_copy
    - monitoring_build

- hosts: cluster_infra:&master[0]
  remote_user: treeptik

  roles:
    - monitoring_deploy
